# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:05:16+00:00



import argparse
import json
import os
from datetime import date
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBasic
from fastapi import Path, Query
from pydantic import conint, constr
from starlette.requests import Request

from models import (
    Identity,
    NotifyV1Credential,
    NotifyV1Service,
    NotifyV1ServiceBinding,
    NotifyV1ServiceNotification,
    Tag,
    V1CredentialsGetResponse,
    V1ServicesGetResponse,
    V1ServicesServiceSidBindingsGetResponse,
)

app = MCPProxy(
    contact={
        'email': 'support@twilio.com',
        'name': 'Twilio Support',
        'url': 'https://support.twilio.com',
    },
    description='This is the public Twilio REST API.',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    termsOfService='https://www.twilio.com/legal/tos',
    title='Twilio - Notify',
    version='1.42.0',
    servers=[{'url': 'https://notify.twilio.com'}],
)


@app.get(
    '/v1/Credentials',
    tags=['service_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_credential(
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Credentials',
    tags=['service_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_credential(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Credentials/{Sid}',
    tags=['credential_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_credential(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Credentials/{Sid}',
    tags=['credential_management', 'binding_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_credential(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Credentials/{Sid}',
    tags=['credential_management', 'binding_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_credential(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services',
    tags=['service_operations', 'binding_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service(
    friendly_name: Optional[str] = Query(None, alias='FriendlyName'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services',
    tags=['service_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_service(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ServiceSid}/Bindings',
    tags=['service_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_binding(
    service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ServiceSid'),
    start_date: Optional[date] = Query(None, alias='StartDate'),
    end_date: Optional[date] = Query(None, alias='EndDate'),
    identity: Optional[Identity] = Query(None, alias='Identity'),
    tag: Optional[Tag] = Query(None, alias='Tag'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ServiceSid}/Bindings',
    tags=['service_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_binding(
    service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ServiceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Services/{ServiceSid}/Bindings/{Sid}',
    tags=['service_operations', 'binding_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_binding(
    service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ServiceSid'),
    sid: constr(pattern=r'^BS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ServiceSid}/Bindings/{Sid}',
    tags=['service_operations', 'binding_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_binding(
    service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ServiceSid'),
    sid: constr(pattern=r'^BS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ServiceSid}/Notifications',
    tags=['service_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_notification(
    service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ServiceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Services/{Sid}',
    tags=['credential_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_service(
    sid: constr(pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{Sid}',
    tags=['binding_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service(
    sid: constr(pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{Sid}',
    tags=['credential_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_service(
    sid: constr(pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
